id: AB84CAC84
title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:10:07.856557
  last_modified_at: 2022-03-01 01:10:07.856563
